import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`p-4 h-screen bg-blue-600 text-white ${inter.className}`}
      >
        <nav className="flex justify-between">
          <Link href={"/"}>
            <span className="font-bold text-2xl">Vanguard UI</span>
          </Link>
          <div className="flex gap-5">
            <Link href={"/docs"}>Documentation</Link>
            <Link href={"/examples"}>Examples</Link>
            <Link href={"/plugins"}>Plugins</Link>
            <Link href={"/figma"}>Figma</Link>
            <Link href={"/dev/test"}>Dev Test</Link>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
